from . import employee
from . import invoice
from . import jadwal
from . import kelas
from . import kurikulum
from . import master
from . import operasional
from . import partner
from . import pembayaran
from . import product
from . import spmb
from . import wisuda
